parser:
  ignore_headers: ["vendor/*", "test/*"]
  preprocess_macros: true
  max_file_size: 10485760  # 10MB
  
llm:
  model: "gpt-4"
  temperature: 0.2
  max_tokens: 4096
  retry_attempts: 3
  timeout: 30
  
generator:
  use_type_hints: true
  style: "pep8"
  doc_style: "google"
  max_line_length: 88
  generate_tests: true
  
verification:
  max_iterations: 5
  run_tests: true
  strict_imports: true
  static_analysis: true
  
logging:
  level: "INFO"
  file: "c2py.log"
  max_size: 10485760  # 10MB
  backup_count: 5 